clients/lib: include string.h for memset()
Fixes a build warning due to a missing prototype:

  strprop.c: In function 'zalloc':
  strprop.c:13:2: warning: implicit declaration of function 'memset'
      [-Wimplicit-function-declaration]
     13 |  memset(vp, size, 0);
        |  ^~~~~~