clients/lib: include string.h for memcpy()
Fixes a build warning due to a missing prototype:

  malloc.c: In function 'realloc':
  malloc.c:245:3: warning: implicit declaration of function 'memcpy'
      [-Wimplicit-function-declaration]
    245 |   memcpy(newmem, mem, nbytes);
        |   ^~~~~~