forth/wrapper: include time.h
Fixes build warnings due to missing prototypes:

  forth/wrapper/wrapper.c: In function ‘today’:
  forth/wrapper/wrapper.c:2145:2: warning: implicit declaration of function
      ‘time’; did you mean ‘ftime’? [-Wimplicit-function-declaration]
   2145 |  time(&tadd);
        |  ^~~~
        |  ftime
  forth/wrapper/wrapper.c:2146:15: warning: implicit declaration of
      function ‘localtime’ [-Wimplicit-function-declaration]
   2146 |  return((long)localtime(&tadd));
        |               ^~~~~~~~~